---
language: python
services:
  - docker

env:
  global:
    - ROLE_NAME="php_fpm"
  matrix:
    - MOLECULE_DISTRO="centos-7"
    - MOLECULE_DISTRO="centos-8"
    - MOLECULE_DISTRO="debian-9"
    - MOLECULE_DISTRO="debian-10"
    - MOLECULE_DISTRO="ubuntu-16.04"
    - MOLECULE_DISTRO="ubuntu-18.04"

install:
  - pip install ansible ansible-lint docker molecule[docker] testinfra yamllint

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME inmotionhosting.$ROLE_NAME
  - cd inmotionhosting.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
